<?php
/**
 * Configuration holder. Values come from _app/config.local.php, which the
 * installer writes, and from the `settings` table for runtime-editable keys.
 */
final class Config
{
    private static array $data = [];
    private static array $settings = [];
    private static bool $settingsLoaded = false;

    public static function load(): void
    {
        self::$data = [
            'db_host'      => 'localhost',
            'db_port'      => 3306,
            'db_name'      => '',
            'db_user'      => '',
            'db_pass'      => '',
            'app_url'      => '',
            'app_secret'   => '',
            'storage_dir'  => PUBLIC_DIR . '/_storage',
            'max_upload_mb'=> 4096,
            'allow_signup' => true,
            'mail_from'    => '',
            'mail_from_name' => 'MyLoom',
            'smtp_host'    => '',
            'smtp_port'    => 587,
            'smtp_user'    => '',
            'smtp_pass'    => '',
            'smtp_secure'  => 'tls',
            'debug'        => false,
        ];

        if (is_file(CONFIG_FILE)) {
            $local = require CONFIG_FILE;
            if (is_array($local)) {
                self::$data = array_merge(self::$data, $local);
            }
        }

        if (self::$data['app_url'] === '') {
            self::$data['app_url'] = Util::guessBaseUrl();
        }
        self::$data['app_url'] = rtrim(self::$data['app_url'], '/');
    }

    public static function get(string $key, $default = null)
    {
        return self::$data[$key] ?? $default;
    }

    public static function set(string $key, $value): void
    {
        self::$data[$key] = $value;
    }

    public static function all(): array
    {
        return self::$data;
    }

    /** Runtime settings stored in the database (editable from the admin UI). */
    public static function setting(string $key, $default = null)
    {
        if (!self::$settingsLoaded) {
            self::$settingsLoaded = true;
            try {
                foreach (Db::all('SELECT k, v FROM settings') as $row) {
                    self::$settings[$row['k']] = $row['v'];
                }
            } catch (Throwable $e) {
                // Table may not exist yet during installation.
            }
        }
        return self::$settings[$key] ?? $default;
    }

    public static function putSetting(string $key, string $value): void
    {
        Db::run(
            'INSERT INTO settings (k, v) VALUES (?, ?) ON DUPLICATE KEY UPDATE v = VALUES(v)',
            [$key, $value]
        );
        self::$settings[$key] = $value;
    }

    /** Write config.local.php during installation. */
    public static function write(array $values): bool
    {
        $export = var_export($values, true);
        $php = "<?php\n// Generated by the MyLoom installer. Safe to edit by hand.\nreturn {$export};\n";
        return file_put_contents(CONFIG_FILE, $php, LOCK_EX) !== false;
    }
}
